### ISSUE TITLE
Great package needs great static analysis :)

### ISSUE THREAD

**Issue by szepeviktor** [inpsyde/Wonolog#47]
Hello inpsyde people!

Please consider running @phpstan 
It needs modern PHP to run, e.g. 7.3

`phpstan.neon.dist`

```yaml
#$ composer require --dev phpstan/phpstan-shim szepeviktor/phpstan-wordpress
#$ vendor/bin/phpstan analyze

includes:
    - phar://phpstan.phar/conf/bleedingEdge.neon
    - vendor/szepeviktor/phpstan-wordpress/extension.neon
parameters:
    level: max
    inferPrivatePropertyTypeFromConstructor: true
    paths:
        - %currentWorkingDirectory%/src/
    ignoreErrors:
        # Uses func_get_args()
        - '#^Function apply_filters(_ref_array)? invoked with [34567] parameters, 2 required\.$#'
        - '#^Function do_action(_ref_array)? invoked with [3456] parameters, 1-2 required\.$#'
        - '#^Function add_query_arg invoked with [123] parameters?, 0 required\.$#'
```
